version: "3.10"
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - mp3_data:/code/audio
    ports:
      - "8000:8010"
  db:
    image: postgres:15.3
    restart: always
    env_file:
        - app/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5401:5432" # for debuging purposes

volumes:
  db_data:
  mp3_data:
